CREATE DATABASE 'YLBBS' DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci
CREATE TABLE YL_USER_INFO;
CREATE TABLE YL_LOGIN_LOG;
CREATE TABLE YL_ROLE_INFO;
CREATE TABLE YL_MENU_INFO;
CREATE TABLE YL_AUTH_INFO;

